services:
  # Cambiar a MySQL
  mysql:
    image: mysql:8.0
    container_name: app-db-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: nuestrosPaises
      MYSQL_USER: UsuarioAdmin
      MYSQL_PASSWORD: admin123
      MYSQL_ROOT_PASSWORD: root123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: .
    container_name: app-spring
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/nuestrosPaises?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: UsuarioAdmin
      SPRING_DATASOURCE_PASSWORD: admin123
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver

volumes:
  mysql_data: